version: '3.1'
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    ports:
      - "1206:80"
    volumes:
      - /root/filebrowser/filebrowser.db:/database.db
      - /root/filebrowser/.filebrowser.json:/.filebrowser.json
      - filedrive_srv:/srv
    environment:
      - FB_BASEURL=/
    restart: always
    deploy:
        resources:
            limits:
              cpus: "3"
              memory: 4G
volumes:
  filedrive_srv:
