DELETE FROM QualiLabDev.`analyze_test_result_field_formula`;
DELETE FROM QualiLabDev.`analyze_test_result_field`;
UPDATE QualiLabDev.`analyze_test_result` SET father_id = null;
DELETE FROM QualiLabDev.`analyze_test_result`;
DELETE FROM QualiLabDev.`analyze_cycles`;
UPDATE QualiLabDev.`analyze_component` SET father_id = null;
DELETE FROM QualiLabDev.`analyze_component`;
DELETE FROM QualiLabDev.`analyze_test`;
DELETE FROM QualiLabDev.`request`;
DELETE FROM QualiLabDev.`analyze`;
DELETE FROM QualiLabDev.`audit_trail`;
DELETE FROM QualiLabDev.`product_test`;
DELETE FROM QualiLabDev.`test_component`;
DELETE FROM QualiLabDev.`test_result`;
DELETE FROM QualiLabDev.`test`;
DELETE FROM QualiLabDev.`product`;
DELETE FROM QualiLabDev.`formula_body`;
DELETE FROM QualiLabDev.`formula_variable`;
DELETE FROM QualiLabDev.`result`;
UPDATE QualiLabDev.formula SET parent_id = null;
DELETE FROM QualiLabDev.`formula`;
DELETE FROM QualiLabDev.`measure`;
DELETE FROM QualiLabDev.`component`;
DELETE FROM QualiLabDev.`result`;
DELETE FROM QualiLabDev.`measure`;
