DELETE FROM QualiLabHML.`analyze_test_result_field_formula`;
DELETE FROM QualiLabHML.`analyze_test_result_field`;
UPDATE QualiLabHML.`analyze_test_result` SET father_id = null;
DELETE FROM QualiLabHML.`analyze_test_result`;
DELETE FROM QualiLabHML.`analyze_cycles`;
UPDATE QualiLabHML.`analyze_component` SET father_id = null;
DELETE FROM QualiLabHML.`analyze_component`;
DELETE FROM QualiLabHML.`analyze_test`;
DELETE FROM QualiLabHML.`request`;
DELETE FROM QualiLabHML.`analyze`;
DELETE FROM QualiLabHML.`audit_trail`;
DELETE FROM QualiLabHML.`product_test`;
DELETE FROM QualiLabHML.`test_component`;
DELETE FROM QualiLabHML.`test_result`;
DELETE FROM QualiLabHML.`test`;
DELETE FROM QualiLabHML.`product`;
DELETE FROM QualiLabHML.`formula_body`;
DELETE FROM QualiLabHML.`formula_variable`;
DELETE FROM QualiLabHML.`result`;
UPDATE QualiLabHML.formula SET parent_id = null;
DELETE FROM QualiLabHML.`formula`;
DELETE FROM QualiLabHML.`measure`;
DELETE FROM QualiLabHML.`component`;
DELETE FROM QualiLabHML.`result`;
DELETE FROM QualiLabHML.`measure`;
