DELETE FROM QualiLabPRD.`analyze_test_result_field_formula`;
DELETE FROM QualiLabPRD.`analyze_test_result_field`;
UPDATE QualiLabPRD.`analyze_test_result` SET father_id = null;
DELETE FROM QualiLabPRD.`analyze_test_result`;
DELETE FROM QualiLabPRD.`analyze_cycles`;
UPDATE QualiLabPRD.`analyze_component` SET father_id = null;
DELETE FROM QualiLabPRD.`analyze_component`;
DELETE FROM QualiLabPRD.`analyze_test`;
DELETE FROM QualiLabPRD.`request`;
DELETE FROM QualiLabPRD.`analyze`;
DELETE FROM QualiLabPRD.`audit_trail`;
DELETE FROM QualiLabPRD.`product_test`;
DELETE FROM QualiLabPRD.`test_component`;
DELETE FROM QualiLabPRD.`test_result`;
DELETE FROM QualiLabPRD.`test`;
DELETE FROM QualiLabPRD.`product`;
DELETE FROM QualiLabPRD.`formula_body`;
DELETE FROM QualiLabPRD.`formula_variable`;
DELETE FROM QualiLabPRD.`result`;
UPDATE QualiLabPRD.formula SET parent_id = null;
DELETE FROM QualiLabPRD.`formula`;
DELETE FROM QualiLabPRD.`measure`;
DELETE FROM QualiLabPRD.`component`;
DELETE FROM QualiLabPRD.`result`;
DELETE FROM QualiLabPRD.`measure`;
